//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmaster3000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookAuthor
    {
        public int id { get; set; }
        public int BookId { get; set; }
        public int AuthorId { get; set; }
    
        public virtual author author { get; set; }
        public virtual book book { get; set; }
    }
}
